### ISSUE TITLE
AWS4-HMAC-SHA256 Support

### ISSUE THREAD

**Issue by Techbrunch** [LevelbossMike/ember-deploy-s3#19]
Hello, I'm using a bucket hosted in the Frankfurt region which uses a newer authentication scheme that's not supported.

> Unable to sync: InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

More info in this stackoverflow answer: http://stackoverflow.com/a/26538266/1447468

**Comment by LevelbossMike** [comment]
This is unfortunately a problem with the s3 library this addon is using. https://github.com/LevelbossMike/ember-deploy-s3/issues/12

This will be fixed with the upcoming version of ember-cli-deploy and the new s3 addon. Right now the only workaround is to use a region that supports older API versions (e.g ireland) which should not make a difference in the context of an Ember deploy.

**Comment by Techbrunch** [comment]
Thanks but I think you should not close this issue until the new s3 addon is released or else people will keep creating issues.
