### ISSUE TITLE
Set Cache-Control: no-cache on development builds

### ISSUE THREAD

**Issue by andrewbranch** [LevelbossMike/ember-deploy-s3#20]
This adapter sets “basically cache this forever” headers on assets, which is great for fingerprinted assets, but is bad for a development build, when your assets are just `my-app.js` and `vendor.js`, etc. Can we set ”don’t cache this at all” headers on non-fingerprinted assets? Or maybe on everything when the environment is not `production`?

**Comment by LevelbossMike** [comment]
This came up multiple times already in some form or another but I honestly don't get why anyone would upload their development builds to s3. Can you provide some insight why one would like to 'deploy' the development build?

**Comment by andrewbranch** [comment]
Yep! At work, we have historically had three web environments: production, staging, and development. Development is distinguished from staging in that it can be used for new, experimental, unapproved, or unstable features, while staging typically mirrors production exactly, or rather, mirrors what production is _about_ to be. So, staging, of course, would be a production build. On the development server though, it can be helpful to have extra debugging and logging information. The real reason for me, though, is the way we set environment variables in `config/environment.js`. In a development build, we set an `API_HOST` variable that points to our _development_ API server, which connects to our _development_ database.

But, from the perspective of this adapter, I kind of feel like all this is a little beside the point. The point is, or so it seems to me, that ember-cli-deploy supports the `buildEnv` option, therefore adapters for ember-cli-deploy should work if the user chooses to change that option.

**Comment by LevelbossMike** [comment]
I think the way to go is just to setup a production like build in this scenario and deploy that as you basically want to do the same thing as in a staging scenario. As far as I know you can tweak the Ember.Logger (or maybe you just have to use that instead of console.log) to be around in a production-like build as well. This is most likely a setting int `environment.js`.

Honestly I am just against this because I think it's bad practice and should be solved in another way and I don't want to promote this for other users.

If that's something you really need I can be convinced to merge that though. Have you looked into using Ember.Logger for debug output?

**Comment by andrewbranch** [comment]
Don’t merge it because I need it—I’m using my fork directly now. But if you aren’t going to support non-production builds, I think the adapter should stop the deployment and log to the console. Allowing development builds but marking assets as cacheable creates problems, and it’s not super easy to diagnose.

So if nothing else, why not put an end to “This came up multiple times already in some form or another...”?

**Comment by LevelbossMike** [comment]
The buildEnv option was added because people needed some environments like 'staging' that do a development like build but behave the same as production and use different api-hosts etc..

As I said it actually does not make much sense to deploy a development build. The way to go here is to setup a production like build and use that. There is a section in the [ember-cli-documentation](http://ember-cli.github.io/ember-cli-deploy/docs/v0.4.x/fingerprinting-options-and-staging-environments/) that goes into detail what you need to do to setup a production like build.

I am closing this for now but feel free to open again and comment on this issue. Happy to help you with your deployment process.

**Comment by LevelbossMike** [comment]
I have now also updated the README about the use of buildEnv. Hope that helps other people that run into the buildEnv development problem.

https://github.com/LevelbossMike/ember-deploy-s3/commit/506f8a98875f96b71338d73c75d2938141b5d407
