### ISSUE TITLE
Pass bucketLocation to node-s3-client

### ISSUE THREAD

**Issue by ghost** [LevelbossMike/ember-deploy-s3#4]
Not all options are passed to node-s3-client, so `bucketLocation` can't be specified. Work around is to use an environment variable `AWS_REGION` instead.

**Comment by joebartels** [comment]
I'd recommend a pre-upload step that confirms/updates any user provided regions: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getBucketLocation-property
happy to do a PR sometime this week if it's an agreeable approach

**Comment by LevelbossMike** [comment]
@Soliah thanks for this issue.

What's the difference of specifying a bucketLocation vs. passing the region option? `ember-deploy-s3` is passing the valid options the s3-api provides to the underlying library. http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property

I didn't want to couple the library to node-s3-client so only the s3 valid options are passed.

**Comment by LevelbossMike** [comment]
@joebartels If you have an idea how to solve this in a user friendly way I'd be happy for a PR. :)

**Comment by ghost** [comment]
@LevelbossMike ah looks like I was only referring to the node-s3-client docs, but didn't realise that I could use the AWS SDK options instead.

I ended up just using an environment variable like I mentioned, but will now switch to using the `region` key.

**Comment by ziggythehamster** [comment]
I would just remove the AKID/SAK from the docs and suggest visiting http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html for a list of configuration methods. I prefer `AWS_PROFILE` passed in on the command line and IAM instance roles because that centralizes the configuration and mitigates accidental AKID/SAK leaking (i.e., if you accidentally make your repo public, and you committed the config, you don't give everyone your AKID/SAK).
